In [221]:
from sklearn.linear_model import LogisticRegression as LR
import pandas as pd
import numpy as np
import csv

load_data = pd.read_csv('DataAfterClean.csv')
data_array = np.array(load_data)
for line in data_array:
    if line[0] == 'lose':
        line[0] = 1
    else:
        line[0] = 0
    if line[1] == 'LMS': 
        line[2:-10] = line[2:-10]*0.7
    if line[1] == 'LCS' or line[1] == 'LEC':
        line[2:-10] = line[2:-10]*0.8
pd_data = pd.DataFrame(data_array)
pd_data.drop(axis=1, columns=1, inplace=True)

print(pd_data)
pd_data.to_csv('dataAfterHash.csv')

    0     2     3     4     5     6     7     8     9     10  ...     42  \
0    1  4.32  2.88  1.28     4  2.56     2  2.24  5.12  5.36  ...  0.683   
1    0  2.64  2.32  1.92  3.92  2.16   1.6  2.08     4  2.88  ...  0.714   
2    0  2.64  2.32  1.92  3.92  2.16   1.6  2.08     4  2.88  ...  0.714   
3    1   2.8   1.6   1.2  2.64   1.6  0.96  2.16  3.36  2.32  ...  0.664   
4    0   2.8   1.6   1.2  2.64   1.6  0.96  2.16  3.36  2.32  ...  0.664   
5    1  2.64  2.48  1.68  3.04  3.52   1.6  1.36  4.24  2.88  ...  0.703   
6    1  2.64  2.48  1.68  3.04  3.52   1.6  1.36  4.24  2.88  ...  0.703   
7    1  2.88  2.16  1.52  3.12  1.92  1.04  2.72  5.44  2.16  ...  0.682   
8    1  2.88  2.16  1.52  3.12  1.92  1.04  2.72  5.44  2.16  ...  0.682   
9    1  3.76  2.16  1.12  3.28     2   1.6  2.08   3.6  2.72  ...  0.655   
10   0  3.76  2.16  1.12  3.28     2   1.6  2.08   3.6  2.72  ...  0.655   
11   1   3.6  1.68  0.96  2.64  2.16  1.92  1.92  3.28  2.16  ...  0.628   
12   1   3.6

In [323]:
from sklearn.ensemble import RandomForestClassifier
import random
import numpy as np
import pandas as pd


data_array = np.array(pd_data)
x = data_array[:,1:data_array.shape[1]]
y = data_array[:,0:1]
selection = [v for v in range(len(x)) if v%5 !=0] #traing_data
selection2 = [v for v in range(len(x)) if v%5  == 0] #testing_data

clf = RandomForestClassifier(n_estimators=1000,random_state=33)

x2 = x[selection, :] 
x3 = x[selection2, :]
y2 = y[selection, :]
y3 = y[selection2, :]
y_train = []
y_test = []
for line in y2:
    y_train.append(line[0])
for line in y3:
    y_test.append(line[0])
    
clf = clf.fit(x2, y_train)

y_predict_training = clf.predict(x2)
y_predict_testing = clf.predict(x3)
a1 = 0
a2 = 0
a3 = 0
a4 = 0
for i in range(len(y_train)):
    if y_train[i] == 0 and y_predict_training[i] == 1:
        a1 = a1 + 1
    if y_train[i] == 1 and y_predict_training[i] == 0:
        a2 = a2 + 1
    if y_train[i] == 0 and y_predict_training[i] == 0:
        a3 = a3 + 1
    if y_train[i] == 1 and y_predict_training[i] == 1:
        a4 = a4 + 1
print(a1)
print(a2)
print(a3)
print(a4)
print((a3+a4)/len(y_train))


a1 = 0
a2 = 0
a3 = 0
a4 = 0


for i in range(len(y_test)):
    if y_test[i] == 0 and y_predict_testing[i] == 1:
        a1 = a1 + 1
    if y_test[i] == 1 and y_predict_testing[i] == 0:
        a2 = a2 + 1
    if y_test[i] == 0 and y_predict_testing[i] == 0:
        a3 = a3 + 1
    if y_test[i] == 1 and y_predict_testing[i] == 1:
        a4 = a4 + 1

print(a1)
print(a2)
print(a3)
print(a4)

print((a3+a4)/len(y_test))

44
42
335
334
0.8860927152317881
40
41
53
55
0.5714285714285714


In [319]:
from __future__ import division
from sklearn.linear_model import LogisticRegression as LR
from sklearn.preprocessing import Normalizer
import random
import numpy as np
import pandas as pd
data_array = np.array(pd_data)

x = data_array[:,1:data_array.shape[1]]
y = data_array[:,0:1]
selection = [v for v in range(len(x)) if v%5 !=0] #traing_data
selection2 = [v for v in range(len(x)) if v%5 ==0] #testing_data
print(x)
lr = linear_model.LogisticRegression(penalty = 'l1')
x2 = x[selection, :] 
x3 = x[selection2, :]
y2 = y[selection, :]
y3 = y[selection2, :]
y_train = []
y_test = []
for line in y2:
    y_train.append(line[0])
for line in y3:
    y_test.append(line[0])
print(y_train)
print(len(x2))
lr.fit(x2,y_train)
y_predict_training = lr.predict(x2)
y_predict_testing = lr.predict(x3)
a1 = 0
a2 = 0
a3 = 0
a4 = 0
for i in range(len(y_train)):
    if y_train[i] == 0 and y_predict_training[i] == 1:
        a1 = a1 + 1
    if y_train[i] == 1 and y_predict_training[i] == 0:
        a2 = a2 + 1
    if y_train[i] == 0 and y_predict_training[i] == 0:
        a3 = a3 + 1
    if y_train[i] == 1 and y_predict_training[i] == 1:
        a4 = a4 + 1
print(a1)
print(a2)
print(a3)
print(a4)
print((a3+a4)/len(y_train))


a1 = 0
a2 = 0
a3 = 0
a4 = 0


for i in range(len(y_test)):
    if y_test[i] == 0 and y_predict_testing[i] == 1:
        a1 = a1 + 1
    if y_test[i] == 1 and y_predict_testing[i] == 0:
        a2 = a2 + 1
    if y_test[i] == 0 and y_predict_testing[i] == 0:
        a3 = a3 + 1
    if y_test[i] == 1 and y_predict_testing[i] == 1:
        a4 = a4 + 1

print(a1)
print(a2)
print(a3)
print(a4)

print((a3+a4)/len(y_test))

[[4.32 2.8800000000000003 1.2800000000000002 ... 0.615 0.548 0.621]
 [2.64 2.32 1.92 ... 0.615 0.548 0.621]
 [2.64 2.32 1.92 ... 0.615 0.548 0.621]
 ...
 [4.800000000000001 3.9200000000000004 1.36 ... 0.63 0.654 0.632]
 [2.72 1.92 1.52 ... 0.63 0.654 0.632]
 [2.72 1.92 1.52 ... 0.63 0.654 0.632]]
[0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0,

c:\users\prospace\appdata\local\programs\python\python37\lib\site-packages\sklearn\linear_model\logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)


In [314]:
#!/usr/bin/python
# -*- coding: UTF-8 -*-
from sklearn.externals import joblib
from keras.preprocessing.sequence import pad_sequences
from keras.preprocessing.text import Tokenizer
from keras.layers.merge import concatenate
from keras.models import Sequential, Model
from keras.layers import Dense, Embedding, Activation, merge, Input, Lambda, Reshape
from keras.layers import Convolution1D, Flatten, Dropout, MaxPool1D, GlobalAveragePooling1D
from keras.layers import LSTM, GRU, TimeDistributed, Bidirectional
from keras.utils.np_utils import to_categorical
from keras import initializers
from keras import backend as K
from keras.engine.topology import Layer
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import SGDClassifier
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split
import pandas as pd
import numpy as np
import csv

x = data_array[:,1:data_array.shape[1]]
print(x)
y = []
for line in data_array:
    tmpline = []
    if line[0] == 1:
        tmpline.append(1);
        tmpline.append(0);
    else:
        tmpline.append(0);
        tmpline.append(1);
    y.append(tmpline)

# 划分训练/测试集

X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)



# 将每个词用词典中的数值代替

# One-hot

model = Sequential()
# 全连接层
model.add(Dense(2048, input_shape=(50,), activation='softmax'))
# DropOut层
model.add(Dropout(0.4))
# 全连接层+分类器
#print(y_train)
model.add(Dense(2,activation='softmax'))

model.compile(loss='binary_crossentropy',
              optimizer='adam',
              metrics=['accuracy'])
			  
y_train = np.array(y_train)			  
y_test = np.array(y_test)	
#print(y_train)
#print(y_test)
model.fit(X_train, y_train,
          batch_size=32,
          epochs=20,
          validation_data=(X_test, y_test))
print(model.predict(X_train))



y_predict_training = model.predict(X_train)
y_predict_testing = model.predict(X_test)
a1 = 0
a2 = 0
a3 = 0
a4 = 0
for i in range(len(y_train)):
    if y_train[i][1] > 0.5 and y_predict_training[i][1] < 0.5:
        a1 = a1 + 1
    if y_train[i][1] < 0.5 and y_predict_training[i][1] > 0.5:
        a2 = a2 + 1
    if y_train[i][1] > 0.5 and y_predict_training[i][1] > 0.5:
        a3 = a3 + 1
    if y_train[i][1] < 0.5 and y_predict_training[i][1] < 0.5:
        a4 = a4 + 1
print(a1)
print(a2)
print(a3)
print(a4)
print((a3+a4)/len(y_train))


a1 = 0
a2 = 0
a3 = 0
a4 = 0


for i in range(len(y_test)):
    if y_test[i][1] > 0.5 and y_predict_testing[i][1] < 0.5:
        a1 = a1 + 1
    if y_test[i][1] < 0.5 and y_predict_testing[i][1] > 0.5:
        a2 = a2 + 1
    if y_test[i][1] > 0.5 and y_predict_testing[i][1] > 0.5:
        a3 = a3 + 1
    if y_test[i][1] < 0.5 and y_predict_testing[i][1] < 0.5:
        a4 = a4 + 1

print(a1)
print(a2)
print(a3)
print(a4)
print((a3+a4)/len(y_test))

[[4.32 2.8800000000000003 1.2800000000000002 ... 0.615 0.548 0.621]
 [2.64 2.32 1.92 ... 0.615 0.548 0.621]
 [2.64 2.32 1.92 ... 0.615 0.548 0.621]
 ...
 [4.800000000000001 3.9200000000000004 1.36 ... 0.63 0.654 0.632]
 [2.72 1.92 1.52 ... 0.63 0.654 0.632]
 [2.72 1.92 1.52 ... 0.63 0.654 0.632]]
Train on 755 samples, validate on 189 samples
Epoch 1/20
755/755 [==============================] - 6s 7ms/step - loss: 0.6928 - acc: 0.4901 - val_loss: 0.6923 - val_acc: 0.4974
Epoch 2/20
755/755 [==============================] - 0s 350us/step - loss: 0.6904 - acc: 0.6079 - val_loss: 0.6892 - val_acc: 0.6190
Epoch 3/20
755/755 [==============================] - 0s 359us/step - loss: 0.6844 - acc: 0.7086 - val_loss: 0.6826 - val_acc: 0.6508
Epoch 4/20
755/755 [==============================] - 0s 351us/step - loss: 0.6730 - acc: 0.6967 - val_loss: 0.6752 - val_acc: 0.6085
Epoch 5/20
755/755 [==============================] - 0s 374us/step - loss: 0.6610 - acc: 0.6755 - val_loss: 0.6644 - val_

In [300]:
joblib.dump(model, 'train_model_mlp.m')
joblib.dump(lr, 'train_model_linear.m')
joblib.dump(clf, 'train_model_tree.m')

['train_model_tree.m']

In [217]:
def predict_work(str1, str2):
    all_team_data = pd.read_csv('teamDataAfterClean.csv')
    team_data_array = np.array(all_team_data)
    tmplineRate1 = []
    tmplineRate2 = []
    tmpdataline = []
    dataline = []
    for line in team_data_array:
        if line[0] == str1:
            tmpline2 = line[2:22]
            if line[1] == 'LMS':
                tmpline2 = tmpline2 * 0.7
            if line[1] =='LCS'or line[1] == 'LEC':
                tmpline2 = tmpline2 * 0.8
            tmplineRate1 = line[22:27]
            for x in tmpline2:
                tmpdataline.append(x)

    for line in team_data_array:       
        if line[0] == str2:
            print(line[0],'  ',str2)
            tmpline2 = line[2:22]
            if line[1] == 'LMS':
                tmpline2 = tmpline2 * 0.7
            if line[1] =='LCS'or line[1] == 'LEC':
                tmpline2 = tmpline2 * 0.8
            tmplineRate2 = line[22:27]
            for x in tmpline2:
                tmpdataline.append(x)
                
    #print(tmpdataline)
    for x in tmplineRate1:
        tmpdataline.append(x)
    for x in tmplineRate2:
        tmpdataline.append(x)
        
    print(tmpdataline)
    
    dataline.append(tmpdataline)
    
    final_x = np.array(dataline)
    
    model_mlp = joblib.load('train_model_mlp.m')
    model_linear = joblib.load('train_model_linear.m')
    model_tree = joblib.load('train_model_tree.m')
    result1 = model_mlp.predict(final_x)
    result2 = model_linear.predict(final_x)
    result3 = model_tree.predict(final_x)
    ans = 0
    
    if result1[0][1] > 0.5:
        ans = ans + 1
    else:
        ans = ans - 1
         
    print(ans)
    
    if result2[0] == 1:
        ans = ans + 1
    else:
        ans = ans - 1
    
    print(ans)
    
    if result3[0] == 1:
        ans = ans + 1
    else:
        ans = ans - 1
    
    print(ans)
    
    if ans > 0:
        return 1
    else:
        return 0

print(predict_work('iG','G2'))

G2    G2
[4.4, 4.7, 2.5, 6.4, 4.3, 4.1, 2.8, 7.9, 4.4, 4.0, 2.6, 7.4, 3.6, 1.1, 3.3, 10.6, 2.9, 3.3, 3.2, 6.0, 3.25, 2.4, 0.85, 3.15, 2.3, 1.45, 1.2, 4.05, 2.3, 2.5, 1.2, 3.0, 2.15, 0.5, 1.5, 5.95, 2.15, 1.95, 1.1, 2.85, 0.642, 0.702, 0.665, 0.687, 0.541, 0.633, 0.63, 0.628, 0.724, 0.546]
-1
0
1
1
